all:
	git submodule init && git submodule update
	echo making directories...
	find . -type d -not -name . -a -not -regex '.*/.git/.*' -print -exec mkdir -p ~/{} \;
	echo linking files...
	find . -type f -not -regex ^./README.md$$ -a -not -regex ^./Makefile$$ -a -not -regex '.*/.git/.*' -print -exec ln -f -T '{}' ~/{} \;
